Debian patch for  building .deb file
BitzenyCoreDevelopers/bitzeny pull request #33
Opened 2018-02-10 05:53 UTC by onokatio

2018-02-10 09:14 UTC, ghost requested changes
boo

2018-02-10 09:14 UTC, shirako-jp commented on contrib/debian/bitzeny-qt.desktop
> +Comment[de]=Verbinde mit dem BitXeny peer-to-peer Netzwerk
typo

2018-02-10 09:14 UTC, shirako-jp commented on contrib/debian/bitzeny-qt.desktop
> +Icon=bitzeny128
missing icon

2018-02-10 09:14 UTC, shirako-jp commented on contrib/debian/bitzeny-qt.install
> +share/pixmaps/bitzeny32.xpm usr/share/pixmaps
missing icon

2018-02-10 09:14 UTC, shirako-jp commented on contrib/debian/bitzeny-qt.install
> +share/pixmaps/bitzeny16.xpm usr/share/pixmaps
missing icon

2018-02-10 09:14 UTC, shirako-jp commented on contrib/debian/bitzeny-qt.install
> +share/pixmaps/bitzeny128.png usr/share/pixmaps
missing icon

2018-02-10 13:10 UTC, onokatio commented
Fixed.

2018-02-10 14:39 UTC, shirako-jp commented
> This branch has conflicts that must be resolved
oh...

2018-02-10 15:01 UTC, onokatio commented
Fix icon file name.
So conflict may be solved.

2018-02-10 15:13 UTC, shirako-jp commented
It has not been fixed yet...

2018-02-11 01:35 UTC, onokatio commented
Rebased form z2.0.x branch.

2018-02-11 12:57 UTC, onokatio commented
@hitobb  @shirako-jp plz review.

2018-02-11 13:47 UTC, ghost requested changes
This PR breaks compiling on Travis CI.
https://travis-ci.org/BitzenyCoreDevelopers/bitzeny/builds/340015664

2018-02-11 14:39 UTC, onokatio commented
Fixed.

2018-02-18 02:23 UTC, hitobb submitted a review, later dismissed
LGTM

2018-02-19 10:23 UTC, ghost requested changes
Please squash commits before merging into z2.0.x

2018-02-19 14:02 UTC, onokatio commented
OK

2018-02-20 14:41 UTC, ghost approved these changes
LGTM

2018-02-20 14:47 UTC, merged